implement to extract success-traj
ajy8456/POMDP pull request #34
Opened 2023-01-20 12:10 UTC by ByungJi-Park

1. I added new attribute(self._num_sim_success) in class POMCPOW to collect success trajectories in simulation.
2. Then, whenever trajectories in simulation succeed to reach a goal, they are appended.
3. Furthermore, I made new file(data_process.py) for data processing.
data type for action -> (type:string, target:string, pos:tuple, orn:tuple)
data type for observation -> (img: list, mask:dict[obj:str, list[list[]]])
data type for reward -> float
4. I tried to finish implementing dataloader, if you are getting better I want to talk about this.

2023-01-20 23:24 UTC, ajy8456 requested changes
I think you should mainly check the items below:

- Creating an option to save data or not
- Unnecessary modifications to `fetching_POMDP_primitive_object.py`
- Implementing a code to verify that the data loader is working

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/fetching_POMDP_primitive_object.py
> +
Also, why did you change this part?

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/fetching_POMDP_primitive_object.py
> +    return WeightedParticles(init_belief)
Too

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/fetching_problem_primitive_object.py
> +        pickle.dump(success_trajs_simulation, f)
Why did you save both data before and after processing?

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/fetching_problem_primitive_object.py
> +        pickle.dump(success_trajs_simulation, f)
It seems better to make it possible to set whether to save the data or not according to the configuration.

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/POMCPOW.py
> +                        self._success_traj_sim.append(history)
It seems better to make it possible to set whether to save the data or not according to the configuration.

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/data_process.py
> +        return x
This function will only work for the simplified version of the problem. I think we should consider this when refactoring.

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/data_process.py
> +                r = rest[0]
Is there any case that history has next state?

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/data_process.py
> +class fetching_data(torch.utils.data.Dataset):
Class names in our project should be pascal case.
ex. fetching_data: snake case, FetchingData: pascal case, fetchingData: camel case

2023-01-20 23:24 UTC, ajy8456 commented on Simulation/pybullet_env/data_process.py
> +
Did you test this data loader? I think it will be fail to make batch with different length of data.

2023-01-20 23:56 UTC, ByungJi-Park commented on Simulation/pybullet_env/POMCPOW.py
> +        self._success_traj_sim = []
Oh, I'm sorry that I typed wrong.

2023-01-21 00:04 UTC, ByungJi-Park commented on Simulation/pybullet_env/fetching_problem_primitive_object.py
> +        pickle.dump(success_trajs_simulation, f)
This is for debugging, but I forgot to remove those codes.
Furthermore, let me implement to set storage option in configuration.

2023-01-21 00:06 UTC, ByungJi-Park commented on Simulation/pybullet_env/POMCPOW.py
> +                        self._success_traj_sim.append(history)
You mean saving success trajectory history?
If it's right, let me implement.

2023-01-21 00:11 UTC, ByungJi-Park commented on Simulation/pybullet_env/data_process.py
> +        return x
Okay, let me consider about it.

2023-01-21 00:15 UTC, ByungJi-Park commented on Simulation/pybullet_env/data_process.py
> +                r = rest[0]
**history += ((action, observation, next_state, reward),)**

            if (termination == "success") or (termination == "fail"):

                total_reward = reward
        
                root.num_visits += 1
                root[action].num_visits += 1
                root[action].value = root[action].value + (total_reward - root[action].value) / (root[action].num_visits)
                    
                # ======================== Debug =========================
                if self.config['project_params']['debug']['get_data']:
                    print('_simulate() end')
                    if termination == "success":
                        self._num_sim_success += 1
                        **self._success_traj_sim.append(history)**

When referring to the above code, history has 4 factors which are (action, observation, next_state, reward).
That's why history might have next state, so I wanted to ask there is another way to implement...

2023-01-21 00:16 UTC, ByungJi-Park commented on Simulation/pybullet_env/data_process.py
> +class fetching_data(torch.utils.data.Dataset):
Oh, I didn't know that. Let me fix it.

2023-01-21 00:22 UTC, ByungJi-Park commented on Simulation/pybullet_env/data_process.py
> +
It will not fail, because data type is list which each success trajectory's type is dictionary. -> [dict, dict, dict ... dict]  
Therefore, even though the length of each success trajectory is different, it's fine. (Also, I have already tested.)
I'd like to ask if I did it right.

2023-01-21 00:26 UTC, ByungJi-Park commented on Simulation/pybullet_env/fetching_POMDP_primitive_object.py
> +            return prob
Actually, I never touched those parts, so it's very weird situation.
One possibility is git clone wrong part at first.
Thus, can I just modify while referring to your code in main branch?

2023-01-21 00:26 UTC, ByungJi-Park commented on Simulation/pybullet_env/fetching_POMDP_primitive_object.py
> +
This is also same situation.

2023-01-21 00:27 UTC, ByungJi-Park commented on Simulation/pybullet_env/fetching_POMDP_primitive_object.py
> +    return WeightedParticles(init_belief)
This is also same situation.

2023-01-22 10:10 UTC, ajy8456 commented on Simulation/pybullet_env/fetching_POMDP_primitive_object.py
> +            return prob
You should commit only parts that you modified or implemented.

2023-01-22 10:14 UTC, ajy8456 commented on Simulation/pybullet_env/POMCPOW.py
> +                        self._success_traj_sim.append(history)
It is the same as the comment above.

2023-01-22 10:17 UTC, ajy8456 commented on Simulation/pybullet_env/data_process.py
> +                r = rest[0]
You'd better leave an comment to make it easier for others to understand.

2023-01-22 10:18 UTC, ajy8456 commented on Simulation/pybullet_env/data_process.py
> +class fetching_data(torch.utils.data.Dataset):
I should have told you. It would be helpful if you write code considering uniformity when doing programming collaboration.

2023-01-22 10:58 UTC, ajy8456 commented on Simulation/pybullet_env/data_process.py
> +
What is the structure of the data processed through the data loader? As far as I know, Pytorch dataloader basically puts data in the list unless you implement processing to stack data in batches of different lengths. One of the roles of the Pytorch dataloader is to match the interface of the input that enters the network. We have to stack the data in batches to learn. So the data loader has to make the sampled data the same size, stack them in batches, and make them into one tensor.

2023-01-25 05:28 UTC, closed without merging