[Add] DataLoader with virtual point sampling.
ajy8456/POMDP pull request #46
Opened 2023-02-21 10:20 UTC by ssh98son

This branch will bring the following features
- DataLoader
- Pick architecture
- Loss (Cross-entropy)
- Training script

Current PR includes:
- DataLoader: I virtually labeled the target point in the observation which is the closest to the object's center.

2023-02-21 10:54 UTC, ajy8456 requested changes

2023-02-21 10:54 UTC, ajy8456 commented on Simulation/pybullet_env/learning/dataset/policy_dataset.py
> +class PolicyDatasetSE2(Dataset):
Why did you name it SE2 separately? Isn't it compatible with SE3? I think it will be compatible with SE3.

2023-02-21 10:54 UTC, ajy8456 commented on Simulation/pybullet_env/learning/dataset/policy_dataset.py
> +            i = np.random.randint(0, trajectory_length)
If you sample the time step in the `trajectory_length` without any conditions, it seems that you cannot distinguish between when the target action is PICK and when it is PLACE. You should only choose when the target actions are PICK.

2023-02-21 11:00 UTC, ajy8456 commented on Simulation/pybullet_env/learning/model/policy/pointpick.py
> +        """
Please leave comment for returns.

2023-02-21 13:42 UTC, ssh98son commented on Simulation/pybullet_env/learning/dataset/policy_dataset.py
> +            i = np.random.randint(0, trajectory_length)
The wrapping while loop and if condition will filter the "PICK". Please see lines 190~210. If those are confusing, please make an additional comment.

2023-02-21 16:43 UTC, ajy8456 requested changes

2023-02-21 16:43 UTC, ajy8456 commented on Simulation/pybullet_env/learning/dataset/process_policy_data.py
> +class PolicyDataset(Dataset):
I think this name could be overlap with another dataset which contain belief. Isn't it better to change the name to notice that inputs of this dataset is observation.

2023-02-21 16:43 UTC, ajy8456 commented on Simulation/pybullet_env/learning/dataset/process_policy_data.py
> +        config = PolicyDatasetSE2.Config(),
You should change the class name. The name of dataset class is not `PolicyDatasetSE2` anymore.

2023-02-22 06:33 UTC, ajy8456 approved these changes

2023-02-22 08:54 UTC, merged